### ISSUE TITLE
listener fails silently?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [uoracs/node-status#1]
I'm rather rusty on go, but the docs suggest this, presumably if you want to notice errors during TCP server setup.
```
log.Fatal(http.ListenAndServe(":8080", nil))
```

**Comment by lcrownover** [comment]
thanks for pointing that out, some of the logic could be a bit safer for sure, like if the files don't exist.

fixed in https://github.com/uoracs/node-status/commit/e5a9fe1525df98fe7fbb9dc377ca55fd248c3ace
